set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build type")
set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/../modules CACHE PATH "CMake module path")
set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/../toolchain/gcc.cmake CACHE PATH "GCC toolchain")
set(CMAKE_INSTALL_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/artifacts CACHE PATH "Install prefix" FORCE)
